kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev_role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps", "extensions"]
  resources: ["daemon", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
